OHT-32 permissions
fjelltopp/ckanext-oht pull request #5
Opened 2022-06-14 14:17 UTC by jonathansberry

This PR makes some small alterations to CKAN permissions so that datasets are hidden from members of the same organisation.  

The idea is:

- Being a member of the same organisation as the dataset's owner org does not entitle you to view the dataset. 
- Datasets can only be viewed if the user is a collaborator on that dataset, or the creator of the dataset, or the dataset is public. 
- If a user does not have access to view a dataset, they should also not have access to edit that dataset. 
- The above holds true for members, editors and admins of the org, but not for sysadmins (for whom all auth is bypassed anyway).

To this end I have implemented the IPermissionLabels interface, and removed the label "member-<org_id>" from each dataset, meaning that for the purposes of establishing read_permissions the dataset is no longer part of its parent organisation, and members of that organisation will therefore not be able to view the dataset.  I have not bench-marked my changes yet as I do not have access to lots of demo data. However I believe the use of IPermissionLabels interface is an excellent way of ensuring that solr searches remain super fast (because the labels are used in the solr index).  

The auth function for package_update was not so elegant as package_show.  I have chosen to chain to the existing auth function a check that the user can view the package, as we would never want someone to be able to edit a package they are not authorised to view. As package_update is only ever run for a single package, and does not form part of bulk searches, I do not expect this to impact performance in any real way, but this could be checked later down the line. 

I believe with these two small changes we have achieved our goal, and have created a test_suite to allow us to ensure that this is the case. Have I missed any important test cases?

2022-06-14 14:22 UTC, jonathansberry commented on ckanext/oht/plugin.py
> +            labels.append(u'creator-%s' % dataset_obj.creator_user_id)
This is the key code, overriding the behaviour defined here:
https://github.com/ckan/ckan/blob/e10534178b58a5f3ac737505aa2a31450b09ad2e/ckan/lib/plugins.py#L656-L659

2022-06-15 09:33 UTC, tomeksabala requested changes

2022-06-15 09:33 UTC, tomeksabala commented on ckanext/oht/tests/test_auth.py
> +        self.user_2 = factories.User()
```
@pytest.fixture
def users():
return {
"member": factories.User()
"edtor" factories.User()
"edtor_other" factories.User()
 "admin": factories.User()
 }

@pytest.fixture
def organization(users)
         self.org = factories.Organization(
            users=[
                {'name': users['member'], 'capacity': 'member'},
                {'name': users['editor'], 'capacity': 'editor'},
                {'name': users['editor_other'], 'capacity': 'editor'},
                {'name': users['admin'], 'capacity': 'admin'}
            ]
        )


@pytest.mark.parametrize("user_role, has_access", ('member', 'editor', 'admin))
def my_test(users, organization):
   user_1 =users[user_role]
```

2022-06-15 09:33 UTC, tomeksabala commented on ckanext/oht/plugin.py
> +def _package_update_auth_function(context, data_dict):
wrap it up with:
```
@logic.auth_disallow_anonymous_access
def _package_update_auth_function(context, data_dict):
```
and then you can remove
```
if user_obj:
```

2022-06-15 14:50 UTC, merged